version: '3.6'

volumes:
  log-data:
    external:
      name: logs-data-services

services:
  gerador-logs:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - log-data:/logs
      - .:/app
      